//
//  BadgeCatalog.swift
//  Replog
//
//  The collection. Static, ordered, and the single source of truth for what exists.
//
//  Shaped by a few rules that the research on achievement systems is consistent about:
//
//  - **Ladders, not one-offs.** Most badges sit on a rung of a series with the next rung
//    visibly close. Tier and shape escalate with the number; the motif stays constant down
//    a ladder so the progression is recognisable on a grid.
//  - **Earned, not handed out.** Nothing rewards volume for its own sake, unsafe training,
//    or bodyweight loss. Nothing is ever taken away, and no copy names a lapse.
//  - **A few stay hidden.** The Curiosities family exists so the collection keeps a tail of
//    things the athlete did not know to chase.
//
//  Ids are persisted on awards, so once shipped an id never changes. Copy may.
//

import Foundation

enum BadgeCatalog {

    /// Every badge, grouped by family in display order.
    static let all: [Badge] = foundations + rhythm + strength + work + atlas + craft + curiosities

    static func badge(id: String) -> Badge? { byID[id] }

    static let byID: [String: Badge] = Dictionary(all.map { ($0.id, $0) },
                                                  uniquingKeysWith: { first, _ in first })

    static func badges(in family: BadgeFamily) -> [Badge] { all.filter { $0.family == family } }

    // MARK: - Foundations: sessions finished

    private static let foundations: [Badge] = [
        Badge(id: "dayOne", name: "Day One", family: .foundations, tier: .bronze,
              shape: .circle, motif: .ascendingSteps, palette: "bronzePlate",
              criterion: .workouts(1),
              hint: "Finish your first workout.",
              meaning: "The first session is the one most people never log. Everything else in this collection is built on it."),
        Badge(id: "fiveLogged", name: "Five Logged", family: .foundations, tier: .bronze,
              shape: .oval, motif: .ascendingSteps, palette: "bronzeOlympic",
              criterion: .workouts(5),
              hint: "Finish five workouts.",
              meaning: "Five sessions is where training stops being a decision each time and starts being a thing you do."),
        Badge(id: "tenLogged", name: "Ten Logged", family: .foundations, tier: .bronze,
              shape: .rect, motif: .ascendingSteps, palette: "bronzeForged",
              criterion: .workouts(10),
              hint: "Finish ten workouts.",
              meaning: "Ten sessions in the log is enough history for the coach to start reading your progression rather than guessing it."),
        Badge(id: "twentyFiveLogged", name: "Twenty-Five Logged", family: .foundations, tier: .silver,
              shape: .triangle, motif: .ascendingSteps, palette: "steelBrushed",
              criterion: .workouts(25),
              hint: "Finish twenty-five workouts.",
              meaning: "Twenty-five sessions is a real training block. The loads you are lifting now were set by you, not estimated for you."),
        Badge(id: "fiftyLogged", name: "Fifty Logged", family: .foundations, tier: .silver,
              shape: .shield, motif: .ascendingSteps, palette: "steelChrome",
              criterion: .workouts(50),
              hint: "Finish fifty workouts.",
              meaning: "Fifty sessions. Most training logs are abandoned long before this."),
        Badge(id: "oneHundredLogged", name: "The Hundred", family: .foundations, tier: .gold,
              shape: .hexagon, motif: .ascendingSteps, palette: "goldOlympic",
              criterion: .workouts(100),
              hint: "Finish one hundred workouts.",
              meaning: "A hundred finished sessions is a serious training history, and a record of a hundred separate decisions to show up."),
        Badge(id: "twoFiftyLogged", name: "Two Fifty", family: .foundations, tier: .jewel,
              shape: .diamond, motif: .ascendingSteps, palette: "sapphire",
              criterion: .workouts(250),
              hint: "Finish two hundred and fifty workouts.",
              meaning: "At this point training is simply part of your week, and the numbers in your plan are the product of years of your own work."),
        Badge(id: "fiveHundredLogged", name: "Five Hundred", family: .foundations, tier: .elite,
              shape: .starburst, motif: .ascendingSteps, palette: "obsidian",
              criterion: .workouts(500),
              hint: "Finish five hundred workouts.",
              meaning: "Five hundred sessions. This is the badge of somebody who trains, full stop."),
    ]

    // MARK: - Rhythm: showing up on repeat

    private static let rhythm: [Badge] = [
        Badge(id: "threeInARow", name: "Three In A Row", family: .rhythm, tier: .bronze,
              shape: .circle, motif: .chevrons, palette: "bronzePlate",
              criterion: .dayStreak(3),
              hint: "Train three days running.",
              meaning: "Three days in a row is the first proof that a good week is something you can choose rather than something that happens to you."),
        Badge(id: "sevenStraight", name: "Seven Straight", family: .rhythm, tier: .silver,
              shape: .oval, motif: .chevrons, palette: "steelBrushed",
              criterion: .dayStreak(7),
              hint: "Train seven days running.",
              meaning: "A full week of training days without a break. Consistency at this density is what makes the loads climb."),
        Badge(id: "tenStraight", name: "Ten Straight", family: .rhythm, tier: .gold,
              shape: .hexagon, motif: .chevrons, palette: "goldAntique",
              criterion: .dayStreak(10),
              hint: "Train ten days running.",
              meaning: "Ten consecutive training days. Keep an eye on recovery here: a streak is a means, not the goal."),
        Badge(id: "fourteenStraight", name: "Fourteen Straight", family: .rhythm, tier: .jewel,
              shape: .diamond, motif: .chevrons, palette: "emerald",
              criterion: .dayStreak(14),
              hint: "Train fourteen days running.",
              meaning: "Two unbroken weeks. Rare, and worth being deliberate about what comes after it."),
        Badge(id: "thirtyStraight", name: "Thirty Straight", family: .rhythm, tier: .elite,
              shape: .starburst, motif: .chevrons, palette: "violetDeep",
              criterion: .dayStreak(30),
              hint: "Train thirty days running.",
              meaning: "A month without a single break in the chain. Almost nobody gets here."),

        Badge(id: "twoWeeksHeld", name: "Two Weeks Held", family: .rhythm, tier: .bronze,
              shape: .oval, motif: .concentricRings, palette: "bronzeMatte",
              criterion: .weekStreak(2),
              hint: "Complete every scheduled day, two weeks running.",
              meaning: "Two weeks where you did everything your plan asked. This is the metric that actually predicts progress."),
        Badge(id: "fourWeeksHeld", name: "Four Weeks Held", family: .rhythm, tier: .silver,
              shape: .rect, motif: .concentricRings, palette: "steelBlue",
              criterion: .weekStreak(4),
              hint: "Complete every scheduled day, four weeks running.",
              meaning: "A month of full weeks. Long enough for a training block to actually do its job."),
        Badge(id: "eightWeeksHeld", name: "Eight Weeks Held", family: .rhythm, tier: .gold,
              shape: .shield, motif: .concentricRings, palette: "brassGradient",
              criterion: .weekStreak(8),
              hint: "Complete every scheduled day, eight weeks running.",
              meaning: "Eight perfect weeks. Most strength programmes are written to run shorter than this."),
        Badge(id: "fullQuarter", name: "A Full Quarter", family: .rhythm, tier: .jewel,
              shape: .hexagon, motif: .concentricRings, palette: "jade",
              criterion: .weekStreak(12),
              hint: "Complete every scheduled day, twelve weeks running.",
              meaning: "Twelve weeks without dropping a scheduled session. This is what a training year is built from."),
        Badge(id: "halfYearHeld", name: "Twenty-Six Weeks", family: .rhythm, tier: .elite,
              shape: .starburst, motif: .concentricRings, palette: "amethyst",
              criterion: .weekStreak(26),
              hint: "Complete every scheduled day, twenty-six weeks running.",
              meaning: "Half a year of complete weeks. The rarest kind of consistency there is."),

        Badge(id: "firstPerfectWeek", name: "Perfect Week", family: .rhythm, tier: .bronze,
              shape: .circle, motif: .laurel, palette: "bronzeOlympic",
              criterion: .perfectWeeks(1),
              hint: "Complete every scheduled day in one week.",
              meaning: "Every session your plan asked for, done. A plan you actually follow beats a better plan you do not."),
        Badge(id: "tenPerfectWeeks", name: "Ten Perfect Weeks", family: .rhythm, tier: .gold,
              shape: .shield, motif: .laurel, palette: "goldMetallic",
              criterion: .perfectWeeks(10),
              hint: "Complete ten perfect weeks in total.",
              meaning: "Ten weeks where nothing was skipped. They need not be consecutive: what counts is how often you finish what you start."),
        Badge(id: "firstWeekIn", name: "First Week In", family: .rhythm, tier: .bronze,
              shape: .triangle, motif: .peak, palette: "copperBrass",
              criterion: .earlyStart(sessions: 3, withinDays: 7),
              hint: "Train three times in your first week.",
              meaning: "Starting properly matters. Three sessions in week one is the strongest single predictor that you will still be training in month three."),
        Badge(id: "firstMonthIn", name: "First Month In", family: .rhythm, tier: .silver,
              shape: .shield, motif: .peak, palette: "steelChrome",
              criterion: .earlyStart(sessions: 10, withinDays: 30),
              hint: "Train ten times in your first month.",
              meaning: "Ten sessions inside your first month. The habit is built, not borrowed."),
        Badge(id: "sixMonthsActive", name: "Six Months In", family: .rhythm, tier: .gold,
              shape: .hexagon, motif: .peak, palette: "goldAntique",
              criterion: .monthsActive(6),
              hint: "Train in six different months.",
              meaning: "Six separate months with training in them. Life interrupted and you came back anyway."),
        Badge(id: "twelveMonthsActive", name: "Twelve Months In", family: .rhythm, tier: .elite,
              shape: .diamond, motif: .peak, palette: "gunmetal",
              criterion: .monthsActive(12),
              hint: "Train in twelve different months.",
              meaning: "A year with training in every kind of month: the busy ones, the dark ones, the ones you did not feel like it."),
    ]

    // MARK: - Strength: beating your own numbers

    private static let strength: [Badge] = [
        Badge(id: "firstBest", name: "First Best", family: .strength, tier: .bronze,
              shape: .circle, motif: .rays, palette: "bronzeForged",
              criterion: .personalBests(1),
              hint: "Set a personal best on any lift.",
              meaning: "Your first recorded best. From here every session has something to beat."),
        Badge(id: "betterAgain", name: "Better Again", family: .strength, tier: .bronze,
              shape: .oval, motif: .rays, palette: "bronzeOlympic",
              criterion: .personalBests(2),
              hint: "Set a second personal best.",
              meaning: "Two bests means the first was not luck. This is progressive overload, working."),
        Badge(id: "fiveBests", name: "Five Bests", family: .strength, tier: .silver,
              shape: .rect, motif: .rays, palette: "steelBrushed",
              criterion: .personalBests(5),
              hint: "Set five personal bests.",
              meaning: "Five sessions where you beat your own record. The trend line is real."),
        Badge(id: "fifteenBests", name: "Fifteen Bests", family: .strength, tier: .silver,
              shape: .shield, motif: .rays, palette: "silverNavy",
              criterion: .personalBests(15),
              hint: "Set fifteen personal bests.",
              meaning: "Fifteen recorded bests. Progress this steady is a training programme doing exactly what it should."),
        Badge(id: "fortyBests", name: "Forty Bests", family: .strength, tier: .gold,
              shape: .hexagon, motif: .rays, palette: "goldOlympic",
              criterion: .personalBests(40),
              hint: "Set forty personal bests.",
              meaning: "Forty bests. At this stage each one is harder won than the last, which is what makes them worth more."),
        Badge(id: "hundredBests", name: "One Hundred Bests", family: .strength, tier: .elite,
              shape: .starburst, motif: .rays, palette: "rubyGold",
              criterion: .personalBests(100),
              hint: "Set one hundred personal bests.",
              meaning: "A hundred times you have been stronger than you had ever been. That is the whole point of the log."),

        Badge(id: "doubleBest", name: "Double Best", family: .strength, tier: .silver,
              shape: .oval, motif: .flame, palette: "steelChrome",
              criterion: .bestsInOneSession(2),
              hint: "Beat two lifts' bests in one session.",
              meaning: "Two records in a single session. Some days everything moves."),
        Badge(id: "tripleBest", name: "Triple Best", family: .strength, tier: .gold,
              shape: .diamond, motif: .flame, palette: "goldMetallic",
              criterion: .bestsInOneSession(3),
              hint: "Beat three lifts' bests in one session.",
              meaning: "Three records in one session. Rare, and usually the sign of a well-timed deload behind it."),

        Badge(id: "pressYourWeight", name: "Press Your Weight", family: .strength, tier: .silver,
              shape: .triangle, motif: .crossedBars, palette: "steelBlue",
              criterion: .bodyweightMultiple(pattern: .upperPush, times: 1.0),
              hint: "Press your own bodyweight.",
              meaning: "The oldest upper body standard there is: an estimated one rep max on a press equal to what you weigh."),
        Badge(id: "pullYourWeight", name: "Pull Your Weight", family: .strength, tier: .silver,
              shape: .rect, motif: .crossedBars, palette: "silverNavy",
              criterion: .bodyweightMultiple(pattern: .upperPull, times: 1.0),
              hint: "Pull your own bodyweight.",
              meaning: "A pulling one rep max at bodyweight. Balances the pressing standard, which is why coaches ask for both."),
        Badge(id: "squatYourWeight", name: "Squat Your Weight", family: .strength, tier: .silver,
              shape: .shield, motif: .crossedBars, palette: "brassBronze",
              criterion: .bodyweightMultiple(pattern: .lowerCompound, times: 1.0),
              hint: "Squat your own bodyweight.",
              meaning: "Bodyweight on the bar. The classic first milestone of lower body strength."),
        Badge(id: "squatOneAndHalf", name: "One And A Half", family: .strength, tier: .gold,
              shape: .hexagon, motif: .crossedBars, palette: "goldAntique",
              criterion: .bodyweightMultiple(pattern: .lowerCompound, times: 1.5),
              hint: "Squat one and a half times your bodyweight.",
              meaning: "One and a half times bodyweight is where lower body strength stops being general fitness and starts being strength."),
        Badge(id: "squatDouble", name: "Double Bodyweight", family: .strength, tier: .jewel,
              shape: .diamond, motif: .crossedBars, palette: "rubyDeep",
              criterion: .bodyweightMultiple(pattern: .lowerCompound, times: 2.0),
              hint: "Squat twice your bodyweight.",
              meaning: "Twice bodyweight on a lower body compound. An advanced standard by any table you look it up in."),
    ]

    // MARK: - Work: honest volume

    private static let work: [Badge] = [
        Badge(id: "tenTonnes", name: "Ten Tonnes", family: .work, tier: .bronze,
              shape: .circle, motif: .bars, palette: "bronzeMatte",
              criterion: .tonnage(10_000),
              hint: "Move ten tonnes in total.",
              meaning: "Ten thousand kilograms through your hands. Roughly a city bus."),
        Badge(id: "fiftyTonnes", name: "Fifty Tonnes", family: .work, tier: .bronze,
              shape: .oval, motif: .bars, palette: "bronzeForged",
              criterion: .tonnage(50_000),
              hint: "Move fifty tonnes in total.",
              meaning: "Fifty tonnes lifted. Heavier than a loaded semi truck, one set at a time."),
        Badge(id: "hundredTonnes", name: "One Hundred Tonnes", family: .work, tier: .silver,
              shape: .rect, motif: .bars, palette: "steelBrushed",
              criterion: .tonnage(100_000),
              hint: "Move one hundred tonnes in total.",
              meaning: "A hundred tonnes. More than a fully loaded Boeing 737 at takeoff."),
        Badge(id: "fiveHundredTonnes", name: "Five Hundred Tonnes", family: .work, tier: .gold,
              shape: .shield, motif: .bars, palette: "goldMetallic",
              criterion: .tonnage(500_000),
              hint: "Move five hundred tonnes in total.",
              meaning: "Half a million kilograms, accumulated one rep at a time over a long time."),
        Badge(id: "thousandTonnes", name: "One Thousand Tonnes", family: .work, tier: .jewel,
              shape: .diamond, motif: .bars, palette: "sapphire",
              criterion: .tonnage(1_000_000),
              hint: "Move one thousand tonnes in total.",
              meaning: "A million kilograms. There is no shortcut to this number; it is only ever years of sets."),

        Badge(id: "bigSession", name: "Heavy Day", family: .work, tier: .silver,
              shape: .triangle, motif: .peak, palette: "steelChrome",
              criterion: .sessionTonnage(10_000),
              hint: "Move ten tonnes in a single session.",
              meaning: "Ten tonnes in one workout. A genuinely big day of work."),
        Badge(id: "hugeSession", name: "Monster Day", family: .work, tier: .gold,
              shape: .starburst, motif: .peak, palette: "brassGradient",
              criterion: .sessionTonnage(20_000),
              hint: "Move twenty tonnes in a single session.",
              meaning: "Twenty tonnes in one session. Make sure the week around it earns the recovery."),

        Badge(id: "fiftySets", name: "Fifty Sets", family: .work, tier: .bronze,
              shape: .triangle, motif: .grid, palette: "bronzePlate",
              criterion: .sets(50),
              hint: "Log fifty sets.",
              meaning: "Fifty completed sets. Sets, not kilograms, are the unit training is actually prescribed in."),
        Badge(id: "fiveHundredSets", name: "Five Hundred Sets", family: .work, tier: .silver,
              shape: .hexagon, motif: .grid, palette: "steelBlue",
              criterion: .sets(500),
              hint: "Log five hundred sets.",
              meaning: "Five hundred sets of practice. Technique is built here, not in any single session."),
        Badge(id: "twoThousandSets", name: "Two Thousand Sets", family: .work, tier: .gold,
              shape: .starburst, motif: .grid, palette: "goldOlympic",
              criterion: .sets(2000),
              hint: "Log two thousand sets.",
              meaning: "Two thousand sets. Somewhere in there the movements stopped being something you think about."),
        Badge(id: "tenThousandReps", name: "Ten Thousand Reps", family: .work, tier: .silver,
              shape: .oval, motif: .wave, palette: "silverNavy",
              criterion: .reps(10_000),
              hint: "Log ten thousand reps.",
              meaning: "Ten thousand repetitions. The number people like to quote about mastery, actually counted."),
        Badge(id: "fiftyThousandReps", name: "Fifty Thousand Reps", family: .work, tier: .jewel,
              shape: .diamond, motif: .wave, palette: "jade",
              criterion: .reps(50_000),
              hint: "Log fifty thousand reps.",
              meaning: "Fifty thousand reps. At this point the log is a biography."),
        Badge(id: "longHaul", name: "Long Haul", family: .work, tier: .silver,
              shape: .rect, motif: .flame, palette: "brassBronze",
              criterion: .sessionMinutes(90),
              hint: "Train for ninety minutes in one session.",
              meaning: "Ninety minutes under the bar in one go. Long sessions are not automatically better, but some days the work simply takes that long."),
    ]

    // MARK: - Atlas: how much of the gym you have seen

    private static let atlas: [Badge] = [
        Badge(id: "tenLifts", name: "Ten Lifts", family: .atlas, tier: .bronze,
              shape: .circle, motif: .orbit, palette: "bronzeOlympic",
              criterion: .distinctExercises(10),
              hint: "Log ten different exercises.",
              meaning: "Ten different movements tried. Variety early is how you find out what your body actually likes."),
        Badge(id: "thirtyLifts", name: "Thirty Lifts", family: .atlas, tier: .silver,
              shape: .oval, motif: .orbit, palette: "steelBrushed",
              criterion: .distinctExercises(30),
              hint: "Log thirty different exercises.",
              meaning: "Thirty movements in your history. Enough that a stalled lift always has a substitute ready."),
        Badge(id: "seventyLifts", name: "Seventy Lifts", family: .atlas, tier: .gold,
              shape: .hexagon, motif: .orbit, palette: "goldAntique",
              criterion: .distinctExercises(70),
              hint: "Log seventy different exercises.",
              meaning: "Seventy distinct movements. You have properly explored the catalogue rather than living in one corner of it."),
        Badge(id: "twentyCompounds", name: "Twenty Compounds", family: .atlas, tier: .gold,
              shape: .triangle, motif: .crossedBars, palette: "brassGradient",
              criterion: .distinctCompounds(20),
              hint: "Log twenty different compound movements.",
              meaning: "Twenty distinct compound lifts. Multi-joint work is where most of the strength and most of the tonnage comes from."),
        Badge(id: "equipmentTour", name: "Equipment Tour", family: .atlas, tier: .silver,
              shape: .rect, motif: .wave, palette: "steelChrome",
              criterion: .distinctEquipment(5),
              hint: "Train with five kinds of equipment.",
              meaning: "Barbells, dumbbells, machines, cables, your own bodyweight. Each one asks something slightly different of you."),
        Badge(id: "fullSweep", name: "Full Sweep", family: .atlas, tier: .gold,
              shape: .shield, motif: .wave, palette: "goldMetallic",
              criterion: .distinctMuscles(10),
              hint: "Train ten different muscle groups.",
              meaning: "Ten muscle groups trained. Whole-body coverage is what keeps a physique balanced and joints happy."),
        Badge(id: "fourDisciplines", name: "Four Disciplines", family: .atlas, tier: .jewel,
              shape: .diamond, motif: .wave, palette: "emerald",
              criterion: .distinctCategories(4),
              hint: "Train across four different exercise categories.",
              meaning: "Strength, stretching, plyometrics, cardio and the rest are different skills. Four of them is a genuinely broad athlete."),
        Badge(id: "everyWeekday", name: "Every Weekday", family: .atlas, tier: .silver,
              shape: .circle, motif: .laurel, palette: "silverNavy",
              criterion: .everyWeekday,
              hint: "Train on all seven days of the week at least once.",
              meaning: "Every day of the week has had a session on it at some point. Your training fits your life rather than the other way round."),
        Badge(id: "inventor", name: "Inventor", family: .atlas, tier: .silver,
              shape: .oval, motif: .grid, palette: "copperBrass",
              criterion: .customExercises(3),
              hint: "Create three of your own exercises.",
              meaning: "Three movements the catalogue did not have. Your log now describes how you actually train."),
        Badge(id: "architect", name: "Architect", family: .atlas, tier: .silver,
              shape: .hexagon, motif: .grid, palette: "steelBlue",
              criterion: .plansBuilt(3),
              hint: "Build three plans.",
              meaning: "Three plans built. Knowing when to change the programme is a skill of its own."),
    ]

    // MARK: - Craft: the judgement side

    private static let craft: [Badge] = [
        Badge(id: "bothDirections", name: "Both Directions", family: .craft, tier: .silver,
              shape: .circle, motif: .wave, palette: "steelBrushed",
              criterion: .pushPullBalance(withinPercent: 20, minTonnage: 5_000),
              hint: "Keep pushing and pulling volume within twenty percent of each other.",
              meaning: "Balanced push and pull volume. The single easiest thing to get wrong, and the one most likely to save your shoulders."),
        Badge(id: "fullSpectrum", name: "Full Spectrum", family: .craft, tier: .silver,
              shape: .oval, motif: .bars, palette: "silverNavy",
              criterion: .repRangeSweep,
              hint: "Cover heavy, moderate and high reps in one session.",
              meaning: "Low, middle and high rep ranges in a single session. Different rep ranges build different qualities, and a complete athlete trains all three."),
        Badge(id: "weighedIn", name: "Weighed In", family: .craft, tier: .bronze,
              shape: .rect, motif: .concentricRings, palette: "bronzeMatte",
              criterion: .bodyweightCheckIns(5),
              hint: "Log five bodyweight check-ins.",
              meaning: "Five check-ins. A bodyweight trend is what turns relative strength from a guess into a number."),
        Badge(id: "trendLine", name: "Trend Line", family: .craft, tier: .gold,
              shape: .shield, motif: .concentricRings, palette: "goldAntique",
              criterion: .bodyweightCheckIns(25),
              hint: "Log twenty-five bodyweight check-ins.",
              meaning: "Twenty-five check-ins is a trend rather than a snapshot, which is the only way bodyweight is worth reading at all."),
        Badge(id: "knowsThemselves", name: "Knows Themselves", family: .craft, tier: .silver,
              shape: .triangle, motif: .flame, palette: "steelChrome",
              criterion: .readinessCheckIns(10),
              hint: "Complete ten readiness check-ins.",
              meaning: "Ten honest reports on sleep, soreness and stress. Training that adapts to how you actually feel beats training that ignores it."),
        Badge(id: "weekendWarrior", name: "Weekend Work", family: .craft, tier: .bronze,
              shape: .hexagon, motif: .peak, palette: "bronzePlate",
              criterion: .weekendSessions(10),
              hint: "Train ten times at a weekend.",
              meaning: "Ten weekend sessions. The days it is easiest to skip are the days that separate a plan from a wish."),
        Badge(id: "welcomeBack", name: "Welcome Back", family: .craft, tier: .silver,
              shape: .starburst, motif: .rays, palette: "copperBrass",
              criterion: .comeback(afterDays: 14),
              hint: "Come back and train after two weeks away.",
              meaning: "You came back after a fortnight off. Restarting is harder than continuing, and you did the harder one."),
        Badge(id: "returned", name: "Long Way Back", family: .craft, tier: .gold,
              shape: .diamond, motif: .rays, palette: "brassBronze",
              criterion: .comeback(afterDays: 60),
              hint: "Come back and train after two months away.",
              meaning: "Two months away and you started again anyway. Nothing in this collection is worth more than that."),
    ]

    // MARK: - Curiosities: hidden until they happen

    private static let curiosities: [Badge] = [
        Badge(id: "beforeTheSun", name: "Before The Sun", family: .curiosities, tier: .jewel,
              shape: .triangle, motif: .rays, palette: "jade",
              criterion: .sessionsBefore(hour: 6, count: 5),
              hint: "Something for the very early risers.",
              meaning: "Five sessions started before six in the morning. A gym at that hour belongs to a particular kind of person."),
        Badge(id: "nightShift", name: "Night Shift", family: .curiosities, tier: .jewel,
              shape: .hexagon, motif: .orbit, palette: "amethyst",
              criterion: .sessionsAfter(hour: 22, count: 5),
              hint: "Something for the very late finishers.",
              meaning: "Five sessions started after ten at night. Training around a life that does not leave daylight for it."),
        Badge(id: "coldStorage", name: "Cold Storage", family: .curiosities, tier: .elite,
              shape: .rect, motif: .wave, palette: "gunmetal",
              criterion: .dormantBest(afterDays: 90),
              hint: "Something an old movement can still give you.",
              meaning: "You set a best on a lift you had not touched in three months. Strength built elsewhere carried across, which is what a well-rounded programme does."),
        Badge(id: "cleanSweep", name: "Clean Sweep", family: .curiosities, tier: .elite,
              shape: .starburst, motif: .flame, palette: "rubyRose",
              criterion: .bestsInOneSession(4),
              hint: "Something that happens when everything lines up.",
              meaning: "Four lifts beat their best in a single session. That is a rested, well-fed, well-timed day, and they do not come often."),
        Badge(id: "rareAir", name: "Rare Air", family: .curiosities, tier: .elite,
              shape: .diamond, motif: .peak, palette: "violetDeep",
              criterion: .sessionTonnage(30_000),
              hint: "Something very few sessions ever reach.",
              meaning: "Thirty tonnes moved in a single session. An exceptional day of work by any standard."),
        Badge(id: "dawnPatrol", name: "Dawn Patrol", family: .curiosities, tier: .gold,
              shape: .oval, motif: .ascendingSteps, palette: "goldMetallic",
              criterion: .sessionsBefore(hour: 7, count: 25),
              hint: "Something for a long habit of early mornings.",
              meaning: "Twenty-five sessions before seven. Not a phase, then."),
    ]
}
